package cms.scansource.model.entity

import cms.scansource.model.ScanSource
import cms.scansource.model.dto.ScanSourceDto
import com.github.yanneckreiss.kconmapper.annotations.KConMapper
import java.time.LocalDateTime

@KConMapper(
    toClasses = [ScanSource::class, ScanSourceDto::class],
    fromClasses = [ScanSource::class, ScanSourceDto::class],
)
class ScanSourceEntity(
    val id: Long? = null,
    cameraServer: String,
    cameraPort: Int,
    cameraUser: String,
    cameraPassword: String,
    cameraDirPath: String,
    cameraDirTemporalFormat: String,
    cameraInDirectories: Boolean = true,
    cameraFileNamePattern: String? = null,
    xrayServer: String,
    xrayPort: Int,
    xrayUser: String,
    xrayPassword: String,
    xrayDirPath: String,
    xrayDirTemporalFormat: String,
    xrayInDirectories: Boolean = true,
    xrayFileNamePattern: String? = null,
    scalesServer: String,
    scalesPort: Int,
    scalesUser: String,
    scalesPassword: String,
    scalesDirPath: String,
    scalesDirTemporalFormat: String,
    scalesInDirectories: Boolean = true,
    scalesFileNamePattern: String? = null,
    mapperId: Long,
    val createdBy: String? = null,
    val createdAt: LocalDateTime? = null,
    val updatedBy: String? = null,
    val updatedAt: LocalDateTime? = null,
) : ScanSource(
    cameraServer,
    cameraPort,
    cameraUser,
    cameraPassword,
    cameraDirPath,
    cameraDirTemporalFormat,
    cameraInDirectories,
    cameraFileNamePattern,
    xrayServer,
    xrayPort,
    xrayUser,
    xrayPassword,
    xrayDirPath,
    xrayDirTemporalFormat,
    xrayInDirectories,
    xrayFileNamePattern,
    scalesServer,
    scalesPort,
    scalesUser,
    scalesPassword,
    scalesDirPath,
    scalesDirTemporalFormat,
    scalesInDirectories,
    scalesFileNamePattern,
    mapperId,
)