package core.model

data class Country(
    var alpha2Code: String,
    val phoneCode: String = "",
    val name: String = "",
    val flagResID: Int = 0
)

val countryAlpha2CodeFlagPathMap = mapOf(
    "ad" to "drawable/flags/flag_andorra.png",
    "ae" to "drawable/flags/flag_uae.png",
    "af" to "drawable/flags/flag_afghanistan.png",
    "ag" to "drawable/flags/flag_antigua_and_barbuda.png",
    "ai" to "drawable/flags/flag_anguilla.png",
    "al" to "drawable/flags/flag_albania.png",
    "am" to "drawable/flags/flag_armenia.png",
    "ao" to "drawable/flags/flag_angola.png",
    "aq" to "drawable/flags/flag_antarctica.png",
    "ar" to "drawable/flags/flag_argentina.png",
    "as" to "drawable/flags/flag_american_samoa.png",
    "at" to "drawable/flags/flag_austria.png",
    "au" to "drawable/flags/flag_australia.png",
    "aw" to "drawable/flags/flag_aruba.png",
    "ax" to "drawable/flags/flag_aland.png",
    "az" to "drawable/flags/flag_azerbaijan.png",
    "ba" to "drawable/flags/flag_bosnia.png",
    "bb" to "drawable/flags/flag_barbados.png",
    "bd" to "drawable/flags/flag_bangladesh.png",
    "be" to "drawable/flags/flag_belgium.png",
    "bf" to "drawable/flags/flag_burkina_faso.png",
    "bg" to "drawable/flags/flag_bulgaria.png",
    "bh" to "drawable/flags/flag_bahrain.png",
    "bi" to "drawable/flags/flag_burundi.png",
    "bj" to "drawable/flags/flag_benin.png",
    "bl" to "drawable/flags/flag_saint_barthelemy.png", // custom
    "bm" to "drawable/flags/flag_bermuda.png",
    "bn" to "drawable/flags/flag_brunei.png",
    "bo" to "drawable/flags/flag_bolivia.png",
    "br" to "drawable/flags/flag_brazil.png",
    "bs" to "drawable/flags/flag_bahamas.png",
    "bt" to "drawable/flags/flag_bhutan.png",
    "bw" to "drawable/flags/flag_botswana.png",
    "by" to "drawable/flags/flag_belarus.png",
    "bz" to "drawable/flags/flag_belize.png",
    "ca" to "drawable/flags/flag_canada.png",
    "cc" to "drawable/flags/flag_cocos.png", // custom
    "cd" to "drawable/flags/flag_democratic_republic_of_the_congo.png",
    "cf" to "drawable/flags/flag_central_african_republic.png",
    "cg" to "drawable/flags/flag_republic_of_the_congo.png",
    "ch" to "drawable/flags/flag_switzerland.png",
    "ci" to "drawable/flags/flag_cote_divoire.png",
    "ck" to "drawable/flags/flag_cook_islands.png",
    "cl" to "drawable/flags/flag_chile.png",
    "cm" to "drawable/flags/flag_cameroon.png",
    "cn" to "drawable/flags/flag_china.png",
    "co" to "drawable/flags/flag_colombia.png",
    "cr" to "drawable/flags/flag_costa_rica.png",
    "cu" to "drawable/flags/flag_cuba.png",
    "cv" to "drawable/flags/flag_cape_verde.png",
    "cw" to "drawable/flags/flag_curacao.png",
    "cx" to "drawable/flags/flag_christmas_island.png",
    "cy" to "drawable/flags/flag_cyprus.png",
    "cz" to "drawable/flags/flag_czech_republic.png",
    "de" to "drawable/flags/flag_germany.png",
    "dj" to "drawable/flags/flag_djibouti.png",
    "dk" to "drawable/flags/flag_denmark.png",
    "dm" to "drawable/flags/flag_dominica.png",
    "do" to "drawable/flags/flag_dominican_republic.png",
    "dz" to "drawable/flags/flag_algeria.png",
    "ec" to "drawable/flags/flag_ecuador.png",
    "ee" to "drawable/flags/flag_estonia.png",
    "eg" to "drawable/flags/flag_egypt.png",
    "er" to "drawable/flags/flag_eritrea.png",
    "es" to "drawable/flags/flag_spain.png",
    "et" to "drawable/flags/flag_ethiopia.png",
    "fi" to "drawable/flags/flag_finland.png",
    "fj" to "drawable/flags/flag_fiji.png",
    "fk" to "drawable/flags/flag_falkland_islands.png",
    "fm" to "drawable/flags/flag_micronesia.png",
    "fo" to "drawable/flags/flag_faroe_islands.png",
    "fr" to "drawable/flags/flag_france.png",
    "ga" to "drawable/flags/flag_gabon.png",
    "gb" to "drawable/flags/flag_united_kingdom.png",
    "gd" to "drawable/flags/flag_grenada.png",
    "ge" to "drawable/flags/flag_georgia.png",
    "gf" to "drawable/flags/flag_guyane.png",
    "gg" to "drawable/flags/flag_guernsey.png",
    "gh" to "drawable/flags/flag_ghana.png",
    "gi" to "drawable/flags/flag_gibraltar.png",
    "gl" to "drawable/flags/flag_greenland.png",
    "gm" to "drawable/flags/flag_gambia.png",
    "gn" to "drawable/flags/flag_guinea.png",
    "gp" to "drawable/flags/flag_guadeloupe.png",
    "gq" to "drawable/flags/flag_equatorial_guinea.png",
    "gr" to "drawable/flags/flag_greece.png",
    "gt" to "drawable/flags/flag_guatemala.png",
    "gu" to "drawable/flags/flag_guam.png",
    "gw" to "drawable/flags/flag_guinea_bissau.png",
    "gy" to "drawable/flags/flag_guyana.png",
    "hk" to "drawable/flags/flag_hong_kong.png",
    "hn" to "drawable/flags/flag_honduras.png",
    "hr" to "drawable/flags/flag_croatia.png",
    "ht" to "drawable/flags/flag_haiti.png",
    "hu" to "drawable/flags/flag_hungary.png",
    "id" to "drawable/flags/flag_indonesia.png",
    "ie" to "drawable/flags/flag_ireland.png",
    "im" to "drawable/flags/flag_isleof_man.png", // custom
    "is" to "drawable/flags/flag_iceland.png",
    "in" to "drawable/flags/flag_india.png",
    "io" to "drawable/flags/flag_british_indian_ocean_territory.png",
    "iq" to "drawable/flags/flag_iraq_new.png",
    "ir" to "drawable/flags/flag_iran.png",
    "it" to "drawable/flags/flag_italy.png",
    "je" to "drawable/flags/flag_jersey.png",
    "jm" to "drawable/flags/flag_jamaica.png",
    "jo" to "drawable/flags/flag_jordan.png",
    "jp" to "drawable/flags/flag_japan.png",
    "ke" to "drawable/flags/flag_kenya.png",
    "kg" to "drawable/flags/flag_kyrgyzstan.png",
    "kh" to "drawable/flags/flag_cambodia.png",
    "ki" to "drawable/flags/flag_kiribati.png",
    "km" to "drawable/flags/flag_comoros.png",
    "kn" to "drawable/flags/flag_saint_kitts_and_nevis.png",
    "kp" to "drawable/flags/flag_north_korea.png",
    "kr" to "drawable/flags/flag_south_korea.png",
    "kw" to "drawable/flags/flag_kuwait.png",
    "ky" to "drawable/flags/flag_cayman_islands.png",
    "kz" to "drawable/flags/flag_kazakhstan.png",
    "la" to "drawable/flags/flag_laos.png",
    "lb" to "drawable/flags/flag_lebanon.png",
    "lc" to "drawable/flags/flag_saint_lucia.png",
    "li" to "drawable/flags/flag_liechtenstein.png",
    "lk" to "drawable/flags/flag_sri_lanka.png",
    "lr" to "drawable/flags/flag_liberia.png",
    "ls" to "drawable/flags/flag_lesotho.png",
    "lt" to "drawable/flags/flag_lithuania.png",
    "lu" to "drawable/flags/flag_luxembourg.png",
    "lv" to "drawable/flags/flag_latvia.png",
    "ly" to "drawable/flags/flag_libya.png",
    "ma" to "drawable/flags/flag_morocco.png",
    "mc" to "drawable/flags/flag_monaco.png",
    "md" to "drawable/flags/flag_moldova.png",
    "me" to "drawable/flags/flag_of_montenegro.png", // custom
    "mf" to "drawable/flags/flag_saint_martin.png",
    "mg" to "drawable/flags/flag_madagascar.png",
    "mh" to "drawable/flags/flag_marshall_islands.png",
    "mk" to "drawable/flags/flag_macedonia.png",
    "ml" to "drawable/flags/flag_mali.png",
    "mm" to "drawable/flags/flag_myanmar.png",
    "mn" to "drawable/flags/flag_mongolia.png",
    "mo" to "drawable/flags/flag_macao.png",
    "mp" to "drawable/flags/flag_northern_mariana_islands.png",
    "mq" to "drawable/flags/flag_martinique.png",
    "mr" to "drawable/flags/flag_mauritania.png",
    "ms" to "drawable/flags/flag_montserrat.png",
    "mt" to "drawable/flags/flag_malta.png",
    "mu" to "drawable/flags/flag_mauritius.png",
    "mv" to "drawable/flags/flag_maldives.png",
    "mw" to "drawable/flags/flag_malawi.png",
    "mx" to "drawable/flags/flag_mexico.png",
    "my" to "drawable/flags/flag_malaysia.png",
    "mz" to "drawable/flags/flag_mozambique.png",
    "na" to "drawable/flags/flag_namibia.png",
    "nc" to "drawable/flags/flag_new_caledonia.png", // custom
    "ne" to "drawable/flags/flag_niger.png",
    "nf" to "drawable/flags/flag_norfolk_island.png",
    "ng" to "drawable/flags/flag_nigeria.png",
    "ni" to "drawable/flags/flag_nicaragua.png",
    "nl" to "drawable/flags/flag_netherlands.png",
    "no" to "drawable/flags/flag_norway.png",
    "np" to "drawable/flags/flag_nepal.png",
    "nr" to "drawable/flags/flag_nauru.png",
    "nu" to "drawable/flags/flag_niue.png",
    "nz" to "drawable/flags/flag_new_zealand.png",
    "om" to "drawable/flags/flag_oman.png",
    "pa" to "drawable/flags/flag_panama.png",
    "pe" to "drawable/flags/flag_peru.png",
    "pf" to "drawable/flags/flag_french_polynesia.png",
    "pg" to "drawable/flags/flag_papua_new_guinea.png",
    "ph" to "drawable/flags/flag_philippines.png",
    "pk" to "drawable/flags/flag_pakistan.png",
    "pl" to "drawable/flags/flag_poland.png",
    "pm" to "drawable/flags/flag_saint_pierre.png",
    "pn" to "drawable/flags/flag_pitcairn_islands.png",
    "pr" to "drawable/flags/flag_puerto_rico.png",
    "ps" to "drawable/flags/flag_palestine.png",
    "pt" to "drawable/flags/flag_portugal.png",
    "pw" to "drawable/flags/flag_palau.png",
    "py" to "drawable/flags/flag_paraguay.png",
    "qa" to "drawable/flags/flag_qatar.png",
    "re" to "drawable/flags/flag_martinique.png", // no exact flag found
    "ro" to "drawable/flags/flag_romania.png",
    "rs" to "drawable/flags/flag_serbia.png", // custom
    "ru" to "drawable/flags/flag_russian_federation.png",
    "rw" to "drawable/flags/flag_rwanda.png",
    "sa" to "drawable/flags/flag_saudi_arabia.png",
    "sb" to "drawable/flags/flag_soloman_islands.png",
    "sc" to "drawable/flags/flag_seychelles.png",
    "sd" to "drawable/flags/flag_sudan.png",
    "se" to "drawable/flags/flag_sweden.png",
    "sg" to "drawable/flags/flag_singapore.png",
    "sh" to "drawable/flags/flag_saint_helena.png", // custom
    "si" to "drawable/flags/flag_slovenia.png",
    "sk" to "drawable/flags/flag_slovakia.png",
    "sl" to "drawable/flags/flag_sierra_leone.png",
    "sm" to "drawable/flags/flag_san_marino.png",
    "sn" to "drawable/flags/flag_senegal.png",
    "so" to "drawable/flags/flag_somalia.png",
    "sr" to "drawable/flags/flag_suriname.png",
    "ss" to "drawable/flags/flag_south_sudan.png",
    "st" to "drawable/flags/flag_sao_tome_and_principe.png",
    "sv" to "drawable/flags/flag_el_salvador.png",
    "sx" to "drawable/flags/flag_sint_maarten.png",
    "sy" to "drawable/flags/flag_syria.png",
    "sz" to "drawable/flags/flag_swaziland.png",
    "tc" to "drawable/flags/flag_turks_and_caicos_islands.png",
    "td" to "drawable/flags/flag_chad.png",
    "tg" to "drawable/flags/flag_togo.png",
    "th" to "drawable/flags/flag_thailand.png",
    "tj" to "drawable/flags/flag_tajikistan.png",
    "tk" to "drawable/flags/flag_tokelau.png", // custom
    "tl" to "drawable/flags/flag_timor_leste.png",
    "tm" to "drawable/flags/flag_turkmenistan.png",
    "tn" to "drawable/flags/flag_tunisia.png",
    "to" to "drawable/flags/flag_tonga.png",
    "tr" to "drawable/flags/flag_turkey.png",
    "tt" to "drawable/flags/flag_trinidad_and_tobago.png",
    "tv" to "drawable/flags/flag_tuvalu.png",
    "tw" to "drawable/flags/flag_taiwan.png",
    "tz" to "drawable/flags/flag_tanzania.png",
    "ua" to "drawable/flags/flag_ukraine.png",
    "ug" to "drawable/flags/flag_uganda.png",
    "us" to "drawable/flags/flag_united_states_of_america.png",
    "uy" to "drawable/flags/flag_uruguay.png",
    "uz" to "drawable/flags/flag_uzbekistan.png",
    "va" to "drawable/flags/flag_vatican_city.png",
    "vc" to "drawable/flags/flag_saint_vicent_and_the_grenadines.png",
    "ve" to "drawable/flags/flag_venezuela.png",
    "vg" to "drawable/flags/flag_british_virgin_islands.png",
    "vi" to "drawable/flags/flag_us_virgin_islands.png",
    "vn" to "drawable/flags/flag_vietnam.png",
    "vu" to "drawable/flags/flag_vanuatu.png",
    "wf" to "drawable/flags/flag_wallis_and_futuna.png",
    "ws" to "drawable/flags/flag_samoa.png",
    "xk" to "drawable/flags/flag_kosovo.png",
    "ye" to "drawable/flags/flag_yemen.png",
    "yt" to "drawable/flags/flag_martinique.png", // no exact flag found
    "za" to "drawable/flags/flag_south_africa.png",
    "zm" to "drawable/flags/flag_zambia.png",
    "zw" to "drawable/flags/flag_zimbabwe.png",
)

val countries = listOf(
    Country("ad", "+376", "Andorra"),
    Country("ae", "+971", "United Arab Emirates (UAE)"),
    Country("af", "+93", "Afghanistan"),
    Country("ag", "+1", "Antigua and Barbuda"),
    Country("ai", "+1", "Anguilla"),
    Country("al", "+355", "Albania"),
    Country("am", "+374", "Armenia"),
    Country("ao", "+244", "Angola"),
    Country("aq", "+672", "Antarctica"),
    Country("ar", "+54", "Argentina"),
    Country("as", "+1", "American Samoa"),
    Country("at", "+43", "Austria"),
    Country("au", "+61", "Australia"),
    Country("aw", "+297", "Aruba"),
    Country("ax", "+358", "Åland Islands"),
    Country("az", "+994", "Azerbaijan"),
    Country("ba", "+387", "Bosnia And Herzegovina"),
    Country("bb", "+1", "Barbados"),
    Country("bd", "+880", "Bangladesh"),
    Country("be", "+32", "Belgium"),
    Country("bf", "+226", "Burkina Faso"),
    Country("bg", "+359", "Bulgaria"),
    Country("bh", "+973", "Bahrain"),
    Country("bi", "+257", "Burundi"),
    Country("bj", "+229", "Benin"),
    Country("bl", "+590", "Saint Barthélemy"),
    Country("bm", "+1", "Bermuda"),
    Country("bn", "+673", "Brunei Darussalam"),
    Country("bo", "+591", "Bolivia, Plurinational State Of"),
    Country("br", "+55", "Brazil"),
    Country("bs", "+1", "Bahamas"),
    Country("bt", "+975", "Bhutan"),
    Country("bw", "+267", "Botswana"),
    Country("by", "+375", "Belarus"),
    Country("bz", "+501", "Belize"),
    Country("ca", "+1", "Canada"),
    Country("cc", "+61", "Cocos (keeling) Islands"),
    Country("cd", "+243", "Congo, The Democratic Republic Of The"),
    Country("cf", "+236", "Central African Republic"),
    Country("cg", "+242", "Congo"),
    Country("ch", "+41", "Switzerland"),
    Country("ci", "+225", "Côte D'ivoire"),
    Country("ck", "+682", "Cook Islands"),
    Country("cl", "+56", "Chile"),
    Country("cm", "+237", "Cameroon"),
    Country("cn", "+86", "China"),
    Country("co", "+57", "Colombia"),
    Country("cr", "+506", "Costa Rica"),
    Country("cu", "+53", "Cuba"),
    Country("cv", "+238", "Cape Verde"),
    Country("cw", "+599", "Curaçao"),
    Country("cx", "+61", "Christmas Island"),
    Country("cy", "+357", "Cyprus"),
    Country("cz", "+420", "Czech Republic"),
    Country("de", "+49", "Germany"),
    Country("dj", "+253", "Djibouti"),
    Country("dk", "+45", "Denmark"),
    Country("dm", "+1", "Dominica"),
    Country("do", "+1", "Dominican Republic"),
    Country("dz", "+213", "Algeria"),
    Country("ec", "+593", "Ecuador"),
    Country("ee", "+372", "Estonia"),
    Country("eg", "+20", "Egypt"),
    Country("er", "+291", "Eritrea"),
    Country("es", "+34", "Spain"),
    Country("et", "+251", "Ethiopia"),
    Country("fi", "+358", "Finland"),
    Country("fj", "+679", "Fiji"),
    Country("fk", "+500", "Falkland Islands (malvinas)"),
    Country("fm", "+691", "Micronesia, Federated States Of"),
    Country("fo", "+298", "Faroe Islands"),
    Country("fr", "+33", "France"),
    Country("ga", "+241", "Gabon"),
    Country("gb", "+44", "United Kingdom"),
    Country("gd", "+1", "Grenada"),
    Country("ge", "+995", "Georgia"),
    Country("gf", "+594", "French Guyana"),
    Country("gh", "+233", "Ghana"),
    Country("gi", "+350", "Gibraltar"),
    Country("gl", "+299", "Greenland"),
    Country("gm", "+220", "Gambia"),
    Country("gn", "+224", "Guinea"),
    Country("gp", "+450", "Guadeloupe"),
    Country("gq", "+240", "Equatorial Guinea"),
    Country("gr", "+30", "Greece"),
    Country("gt", "+502", "Guatemala"),
    Country("gu", "+1", "Guam"),
    Country("gw", "+245", "Guinea-bissau"),
    Country("gy", "+592", "Guyana"),
    Country("hk", "+852", "Hong Kong"),
    Country("hn", "+504", "Honduras"),
    Country("hr", "+385", "Croatia"),
    Country("ht", "+509", "Haiti"),
    Country("hu", "+36", "Hungary"),
    Country("id", "+62", "Indonesia"),
    Country("ie", "+353", "Ireland"),
    Country("im", "+44", "Isle Of Man"),
    Country("is", "+354", "Iceland"),
    Country("in", "+91", "India"),
    Country("io", "+246", "British Indian Ocean Territory"),
    Country("iq", "+964", "Iraq"),
    Country("ir", "+98", "Iran, Islamic Republic Of"),
    Country("it", "+39", "Italy"),
    Country("je", "+44", "Jersey "),
    Country("jm", "+1", "Jamaica"),
    Country("jo", "+962", "Jordan"),
    Country("jp", "+81", "Japan"),
    Country("ke", "+254", "Kenya"),
    Country("kg", "+996", "Kyrgyzstan"),
    Country("kh", "+855", "Cambodia"),
    Country("ki", "+686", "Kiribati"),
    Country("km", "+269", "Comoros"),
    Country("kn", "+1", "Saint Kitts and Nevis"),
    Country("kp", "+850", "North Korea"),
    Country("kr", "+82", "South Korea"),
    Country("kw", "+965", "Kuwait"),
    Country("ky", "+1", "Cayman Islands"),
    Country("kz", "+7", "Kazakhstan"),
    Country("la", "+856", "Lao People's Democratic Republic"),
    Country("lb", "+961", "Lebanon"),
    Country("lc", "+1", "Saint Lucia"),
    Country("li", "+423", "Liechtenstein"),
    Country("lk", "+94", "Sri Lanka"),
    Country("lr", "+231", "Liberia"),
    Country("ls", "+266", "Lesotho"),
    Country("lt", "+370", "Lithuania"),
    Country("lu", "+352", "Luxembourg"),
    Country("lv", "+371", "Latvia"),
    Country("ly", "+218", "Libya"),
    Country("ma", "+212", "Morocco"),
    Country("mc", "+377", "Monaco"),
    Country("md", "+373", "Moldova, Republic Of"),
    Country("me", "+382", "Montenegro"),
    Country("mf", "+590", "Saint Martin"),
    Country("mg", "+261", "Madagascar"),
    Country("mh", "+692", "Marshall Islands"),
    Country("mk", "+389", "Macedonia (FYROM)"),
    Country("ml", "+223", "Mali"),
    Country("mm", "+95", "Myanmar"),
    Country("mn", "+976", "Mongolia"),
    Country("mo", "+853", "Macau"),
    Country("mp", "+1", "Northern Mariana Islands"),
    Country("mq", "+596", "Martinique"),
    Country("mr", "+222", "Mauritania"),
    Country("ms", "+1", "Montserrat"),
    Country("mt", "+356", "Malta"),
    Country("mu", "+230", "Mauritius"),
    Country("mv", "+960", "Maldives"),
    Country("mw", "+265", "Malawi"),
    Country("mx", "+52", "Mexico"),
    Country("my", "+60", "Malaysia"),
    Country("mz", "+258", "Mozambique"),
    Country("na", "+264", "Namibia"),
    Country("nc", "+687", "New Caledonia"),
    Country("ne", "+227", "Niger"),
    Country("nf", "+672", "Norfolk Islands"),
    Country("ng", "+234", "Nigeria"),
    Country("ni", "+505", "Nicaragua"),
    Country("nl", "+31", "Netherlands"),
    Country("no", "+47", "Norway"),
    Country("np", "+977", "Nepal"),
    Country("nr", "+674", "Nauru"),
    Country("nu", "+683", "Niue"),
    Country("nz", "+64", "New Zealand"),
    Country("om", "+968", "Oman"),
    Country("pa", "+507", "Panama"),
    Country("pe", "+51", "Peru"),
    Country("pf", "+689", "French Polynesia"),
    Country("pg", "+675", "Papua New Guinea"),
    Country("ph", "+63", "Philippines"),
    Country("pk", "+92", "Pakistan"),
    Country("pl", "+48", "Poland"),
    Country("pm", "+508", "Saint Pierre And Miquelon"),
    Country("pn", "+870", "Pitcairn Islands"),
    Country("pr", "+1", "Puerto Rico"),
    Country("ps", "+970", "Palestine"),
    Country("pt", "+351", "Portugal"),
    Country("pw", "+680", "Palau"),
    Country("py", "+595", "Paraguay"),
    Country("qa", "+974", "Qatar"),
    Country("re", "+262", "Réunion"),
    Country("ro", "+40", "Romania"),
    Country("rs", "+381", "Serbia"),
    Country("ru", "+7", "Russian Federation"),
    Country("rw", "+250", "Rwanda"),
    Country("sa", "+966", "Saudi Arabia"),
    Country("sb", "+677", "Solomon Islands"),
    Country("sc", "+248", "Seychelles"),
    Country("sd", "+249", "Sudan"),
    Country("se", "+46", "Sweden"),
    Country("sg", "+65", "Singapore"),
    Country("sh", "+290", "Saint Helena, Ascension And Tristan Da Cunha"),
    Country("si", "+386", "Slovenia"),
    Country("sk", "+421", "Slovakia"),
    Country("sl", "+232", "Sierra Leone"),
    Country("sm", "+378", "San Marino"),
    Country("sn", "+221", "Senegal"),
    Country("so", "+252", "Somalia"),
    Country("sr", "+597", "Suriname"),
    Country("ss", "+211", "South Sudan"),
    Country("st", "+239", "Sao Tome And Principe"),
    Country("sv", "+503", "El Salvador"),
    Country("sx", "+1", "Sint Maarten"),
    Country("sy", "+963", "Syrian Arab Republic"),
    Country("sz", "+268", "Swaziland"),
    Country("tc", "+1", "Turks and Caicos Islands"),
    Country("td", "+235", "Chad"),
    Country("tg", "+228", "Togo"),
    Country("th", "+66", "Thailand"),
    Country("tj", "+992", "Tajikistan"),
    Country("tk", "+690", "Tokelau"),
    Country("tl", "+670", "Timor-leste"),
    Country("tm", "+993", "Turkmenistan"),
    Country("tn", "+216", "Tunisia"),
    Country("to", "+676", "Tonga"),
    Country("tr", "+90", "Turkey"),
    Country("tt", "+1", "Trinidad &amp; Tobago"),
    Country("tv", "+688", "Tuvalu"),
    Country("tw", "+886", "Taiwan"),
    Country("tz", "+255", "Tanzania, United Republic Of"),
    Country("ua", "+380", "Ukraine"),
    Country("ug", "+256", "Uganda"),
    Country("us", "+1", "United States"),
    Country("uy", "+598", "Uruguay"),
    Country("uz", "+998", "Uzbekistan"),
    Country("va", "+379", "Holy See (vatican City State)"),
    Country("vc", "+1", "Saint Vincent &amp; The Grenadines"),
    Country("ve", "+58", "Venezuela, Bolivarian Republic Of"),
    Country("vg", "+1", "British Virgin Islands"),
    Country("vi", "+1", "US Virgin Islands"),
    Country("vn", "+84", "Vietnam"),
    Country("vu", "+678", "Vanuatu"),
    Country("wf", "+681", "Wallis And Futuna"),
    Country("ws", "4685", "Samoa"),
    Country("xk", "+383", "Kosovo"),
    Country("ye", "+967", "Yemen"),
    Country("yt", "+262", "Mayotte"),
    Country("za", "+27", "South Africa"),
    Country("zm", "+260", "Zambia"),
    Country("zw", "+263", "Zimbabwe"),
)